All cleanup steps should run

diff --git a/.github/workflows/proxmox.yml b/.github/workflows/proxmox.yml
--- a/.github/workflows/proxmox.yml
+++ b/.github/workflows/proxmox.yml
@@ -55,10 +55,7 @@ jobs:
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2
-      
-       # Remove downloaded ISOs (otherwise packer might fail)
-      - name: Clean up ISOs
-        run: sudo rm /var/lib/vz/template/iso/*
+
       
       - name: Wait for Proxmox to be ready
         run: wget --spider --tries=20 --wait=10 --retry-connrefused --no-check-certificate --retry-on-host-error https://localhost:8006/
@@ -98,12 +95,15 @@ jobs:
         if: ${{ always() }}
         run: |
           # Stop & destroy vms
-          sudo qm stop 300
-          sudo qm destroy 300
+          sudo qm stop 300 || true
+          sudo qm destroy 300 || true
           
           # Destroy templates
-          sudo qm destroy 200
-          sudo qm destroy 201
+          sudo qm destroy 200 || true
+          sudo qm destroy 201 || true
+          
+          # Remove downloaded ISOs (otherwise packer might fail)
+          sudo rm /var/lib/vz/template/iso/* || true
           
           
   teardown:
